input:
  protein_file: "/var/data/proteins/prot_274.fasta"
  spectrum_file: "/var/data/spectra/NOD2_E3.mzML"

search_params:
  # minimum length peptide to look for
  min_peptide_len: 3
  # maximum length peptide to look for
  max_peptide_len: 30
  # tolerance (in ppm) to allow when matching m/z peaks
  ppm_tolerance: 20
  # tolerance (in Da) to allow when matching precursor masses
  precursor_tolerance: 10

spectra_filtering:
  num_peaks: 25
  relative_abundance: 0.01
