name:                hs-hypedsearch
version:             0.1.0.0
github:              "rangelsen/hs-hypedsearch"
license:             BSD3
author:              "Roy Angelsen"
maintainer:          "roy.angelsen@gmail.com"
copyright:           "2022 Roy Angelsen"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rangelsen/hs-hypedsearch#readme>

dependencies:
- base >= 4.7 && < 5
- xml
- yaml
- microlens
- microlens-th
- bytestring
- base64-bytestring
- binary
- containers
- errors

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hs-hypedsearch-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-hypedsearch

tests:
  hs-hypedsearch-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-hypedsearch
    - tasty
    - tasty-hspec
    - hspec
    - hedgehog
    - tasty-hedgehog
